run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - lll
    - staticcheck

linters-settings:
  lll:
    line-length: 100
    tab-width: 4
